services:
  # Reverse proxy on :3000 — single entrypoint for WebUI + API
  reverse-proxy:
    image: nginx:1.27-alpine
    depends_on: [webui, api]
    ports: ["3000:3000"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  api:
    build: ./api
    environment:
      # Connect to LM Studio running natively on macOS
      OPENAI_BASE_URL: "http://host.docker.internal:1234/v1"
      OPENAI_API_KEY: "lm-studio"  # LM Studio accepts any key
      OPENAI_CHAT_MODEL: "local-model"  # LM Studio uses this as model identifier

      CHROMA_URL: "http://chroma:8000"
      REDIS_URL: "redis://redis:6379/0"

      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio12345"
      MINIO_BUCKET: "medrandocs"

      EMBEDDING_MODEL: "BAAI/bge-m3"
      IMAGE_EMBEDDING_MODEL: "sentence-transformers/clip-ViT-B-32"
      OCR_MODEL: "microsoft/trocr-base-printed"
      MAX_CONTEXT_CHARS: "120000"
      ASR_MODEL: "small.en"
    volumes: [ "api_cache:/root/.cache" ]
    expose: ["8080"]   # internal only; no public port
    depends_on:
      chroma:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  webui:
    build: ./simple-ui
    expose: ["80"]     # internal only; no public port
    depends_on: [api]
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:0.4.15
    environment:
      CHROMA_SERVER_HOST: 0.0.0.0
      CHROMA_SERVER_HTTP_PORT: 8000
      ALLOW_RESET: "TRUE"
      CHROMA_SERVER_AUTHN_CREDENTIALS_FILE: ""
      CHROMA_SERVER_AUTHN_PROVIDER: ""
      CHROMA_CLIENT_AUTH_PROVIDER: ""
    volumes: [ "chroma_data:/chroma" ]
    expose: ["8000"]   # internal
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    expose: ["6379"]   # internal
    restart: unless-stopped
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
      MINIO_BROWSER_REDIRECT_URL: http://localhost:3000/minio-console/
    volumes: [ "minio_data:/data" ]
    expose:
      - "9000" # S3 API
      - "9001" # Console
    restart: unless-stopped

volumes:
  chroma_data:
  minio_data:
  api_cache:
